### ISSUE TITLE
Create VisualRust project structure for Rust itself.

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/VisualRust#10]

**Comment by MaulingMonkey** [comment]
I have this partially built.  The biggest caveat is that everything is built - sometimes multiple times - through x.py.  Directly invoking cargo is a no go as it will generate various errors, usually related to accessing forbidden rustc internals.  Of course, we're building rustc...

**Comment by Boddlnagg** [comment]
What is the goal of this? Building rustc is special and different from other projects in a lot of ways ...

**Comment by MaulingMonkey** [comment]
Two goals:

1) To make visual studio usable when hacking on rustc.  This goal was achieved - I used goto definition a lot ;)

2) To stress the limits of VisualRust's project setup and see where the pain points are.  I suppose this was also achieved.  The idea being, if VisualRust can handle something special and different like rustc, it can probably handle everything else we can throw at it.  I ended up creating an nmake project named "x" that wrapped around invoking x.py, but that was the only real bodge/hack I had to resort to.

**Comment by Boddlnagg** [comment]
Okay, this sounds quite nice actually 👍

**Comment by MaulingMonkey** [comment]
The question now is how to best share.

0) Don't - just hoard the project files.
1) Keep a fork around.  This will age poorly.
2) Publish a project skeleton generation script or tool.  Awkward, but might age OK.  Would require a little more work.
3) Try and get them checked into rust-lang/rust itself.  Awkward - they don't have any other IDE project files checked in.  Might get rejected.  *I* might reject it.  Might also just be a variation on 1/2 really.

**Comment by Boddlnagg** [comment]
I'd probably keep it in a branch that you can rebase on a regular basis ... until it can be integrated somewhere in a more official way (either as part of VisualRust or as part of rust-lang/rust).

**Comment by MaulingMonkey** [comment]
https://github.com/MaulingMonkey/rust/tree/x-visual-rust-projects

I'm already 435 commits behind master :smile:
